server:
  port: 8084

spring:
  application:
    name: smartcane-transit
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  profiles:
    active: redis  # 실서버에서는 redis 프로파일 사용
  data:
    redis:
      host: your-redis-host
      port: 6379

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.smartcane.transit: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
sk:
  transit:
    base-url: https://apis.openapi.sk.com # 실제 엔드포인트 넣기
    app-key: YEWVxfrK4j8xTNQZURJ4z1Te4JTZs26v45fgmfn7    # 환경변수/시크릿로 대체 권장

vworld:
  api:
    key: 689FD791-23B2-38BD-86E8-04B77A9B17AF

smartcane:
  transit:
    arriveRadiusWalkM: 14
    arriveRadiusTransitM: 22
    lookAheadWalkM: 25
    geofenceOffRouteM: 28
    medianWindow: 5
    minSpeedMps: 0.3
    arrivalHysteresisN: 1
    description-trigger-m: 120.0