server:
  port: 8084

spring:
  application:
    name: smartcane-transit
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  profiles:
    active: redis  # 실서버에서는 redis 프로파일 사용
  data:
    redis:
      host: your-redis-host
      port: 6379

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.smartcane.transit: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
sk:
  transit:
    base-url: https://apis.openapi.sk.com # 실제 엔드포인트 넣기
    app-key: YEWVxfrK4j8xTNQZURJ4z1Te4JTZs26v45fgmfn7    # 환경변수/시크릿로 대체 권장

vworld:
  api:
    key: 689FD791-23B2-38BD-86E8-04B77A9B17AF


public-data:
  bus:
    base-url: http://apis.data.go.kr/1613000/ArvlInfoInqireService
    service-key: ${PUBLIC_DATA_KEY:your-decoding-key-here} # 환경변수 권장

smartcane:
  transit:
    arriveRadiusWalkM: 15
    arriveRadiusTransitM: 30
    lookAheadWalkM: 25
    geofenceOffRouteM: 28
    medianWindow: 3
    minSpeedMps: 0.3
    arrivalHysteresisN: 1
    description-trigger-m: 120.0

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /docs
    display-request-duration: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    doc-expansion: none
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
