server:
  port: 8084

spring:
  application:
    name: transit-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/smartcane_transit?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: smartcane
    password: smartcane123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none          # 운영에선 Flyway만 사용
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc.time_zone: Asia/Seoul
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  data:
    redis:
      host: localhost
      port: 6379
  security:
    user:
      name: admin
      password: Smartcane1!

vworld:
  api:
    key: 689FD791-23B2-38BD-86E8-04B77A9B17AF

sk:
  transit:
    base-url: https://apis.openapi.sk.com # 실제 엔드포인트 넣기
    app-key: YEWVxfrK4j8xTNQZURJ4z1Te4JTZs26v45fgmfn7    # 환경변수/시크릿로 대체 권장

public-data:
  bus:
    base-url: http://apis.data.go.kr/1613000/ArvlInfoInqireService
    service-key: ${PUBLIC_DATA_KEY:your-decoding-key-here} # 환경변수 권장

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.smartcane.transit: DEBUG
    org.springframework.web.reactive.function.client: DEBUG